import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * home_page.java
 *
 * Created on 27 Oct, 2015, 6:57:46 PM
 */

/**
 *
 * @author ASHU
 */
public class home_page extends javax.swing.JFrame {

    /** Creates new form home_page */
    public home_page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about_us = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        au_back = new javax.swing.JLabel();
        products_page = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jr2 = new javax.swing.JRadioButton();
        jr1 = new javax.swing.JRadioButton();
        jl2 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        pr_back = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        dealership = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jt3 = new javax.swing.JTextField();
        jt4 = new javax.swing.JTextField();
        jt5 = new javax.swing.JTextField();
        jt6 = new javax.swing.JTextField();
        jt7 = new javax.swing.JTextField();
        jt8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jl7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        ds_back = new javax.swing.JLabel();
        empl = new javax.swing.JDialog();
        jButton14 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jl48 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jt21 = new javax.swing.JTextField();
        jt22 = new javax.swing.JTextField();
        jt23 = new javax.swing.JTextField();
        jt24 = new javax.swing.JTextField();
        jt25 = new javax.swing.JTextField();
        jt26 = new javax.swing.JTextField();
        jt27 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jt29 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jt28 = new javax.swing.JPasswordField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jp1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jt10 = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        empl_back = new javax.swing.JLabel();
        report = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta10 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox();
        jButton12 = new javax.swing.JButton();
        jl28 = new javax.swing.JLabel();
        report_back = new javax.swing.JLabel();
        credits = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        administrator = new javax.swing.JDialog();
        jLabel36 = new javax.swing.JLabel();
        jt45 = new javax.swing.JTextField();
        jl45 = new javax.swing.JLabel();
        jt46 = new javax.swing.JPasswordField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta5 = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        admin_back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        about_us.setTitle("About us");
        about_us.setBackground(new java.awt.Color(153, 153, 153));
        about_us.setMinimumSize(new java.awt.Dimension(800, 498));
        about_us.setResizable(false);
        about_us.getContentPane().setLayout(null);

        jTextArea1.setBackground(new java.awt.Color(231, 200, 156));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13));
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setText(" Cement Capacity :\n           23.6 Million Tonnes Per Annum\n\n Multiple Locations :\n           Rajasthan: Beawar, Ras, Khushkhera, Jobner (Jaipur) and Suratgarh\n           Ph:- 9865874125, 2748986\n           Email:-  raj_northzone@shreecement.com\n           Uttarakhand : Laksar (Roorkee)\n           Ph:- 8754126354, 2741356\n           Email:-  uttara_northzone@shreecement.com\n           Bihar : Aurangabad\n           Ph:- 7788546241, 3358974\n           Email:-  bihar_eastzone@shreecement.com\n           Chhattisgarh : Baloda Bazar (Raipur)\n           Ph:- 8874541263, 2789534\n           Email:-  chatt_eastzone@shreecement.com\n           Haryana : Panipat\n           Ph:- 9829612547, 2589634\n           Email:-  har_northzone@shreecement.com\n\n New Projects :\n           Cement grinding unit in Bulandshahr, Uttar Pradesh\n\n Brand Showcase:\n           Shree Ultra\n           Bangur\n           Rockstrong");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 51)));
        jScrollPane1.setViewportView(jTextArea1);

        about_us.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 90, 650, 286);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36));
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("About Us");
        about_us.getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 10, 201, 59);

        jButton19.setBackground(new java.awt.Color(231, 200, 156));
        jButton19.setFont(new java.awt.Font("Arial", 0, 14));
        jButton19.setForeground(new java.awt.Color(204, 0, 0));
        jButton19.setText("CLOSE");
        jButton19.setBorderPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        about_us.getContentPane().add(jButton19);
        jButton19.setBounds(690, 410, 90, 50);

        au_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        about_us.getContentPane().add(au_back);
        au_back.setBounds(0, 0, 850, 500);

        products_page.setTitle("Products Catalogue");
        products_page.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        products_page.setMinimumSize(new java.awt.Dimension(900, 498));
        products_page.setResizable(false);
        products_page.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40));
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Products");
        products_page.getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 10, 230, 50);

        jr2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jr2);
        jr2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jr2.setText("Name");
        jr2.setOpaque(false);
        jr2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jr2ItemStateChanged(evt);
            }
        });
        jr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr2ActionPerformed(evt);
            }
        });
        products_page.getContentPane().add(jr2);
        jr2.setBounds(170, 90, 90, 40);

        jr1.setBackground(new java.awt.Color(231, 200, 156));
        buttonGroup1.add(jr1);
        jr1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jr1.setText("ID");
        jr1.setBorder(null);
        jr1.setOpaque(false);
        jr1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jr1ItemStateChanged(evt);
            }
        });
        jr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr1ActionPerformed(evt);
            }
        });
        products_page.getContentPane().add(jr1);
        jr1.setBounds(20, 90, 80, 40);

        jl2.setVisible(false);
        jl2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
        jl2.setText("Enter Name");
        products_page.getContentPane().add(jl2);
        jl2.setBounds(20, 150, 120, 30);

        jl1.setVisible(false);
        jl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
        jl1.setText("Enter ID");
        products_page.getContentPane().add(jl1);
        jl1.setBounds(20, 150, 130, 30);

        jt1.setVisible(false);
        jt1.setBackground(new java.awt.Color(231, 200, 156));
        jt1.setBorder(null);
        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });
        products_page.getContentPane().add(jt1);
        jt1.setBounds(20, 210, 110, 40);

        jButton4.setBackground(new java.awt.Color(231, 200, 156));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24));
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("Show All");
        jButton4.setToolTipText("fetch all details");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        products_page.getContentPane().add(jButton4);
        jButton4.setBounds(140, 320, 120, 50);

        jt2.setVisible(false);
        jt2.setBackground(new java.awt.Color(231, 200, 156));
        jt2.setBorder(null);
        jt2.setMinimumSize(new java.awt.Dimension(10, 20));
        products_page.getContentPane().add(jt2);
        jt2.setBounds(20, 210, 110, 40);

        jButton1.setBackground(new java.awt.Color(231, 200, 156));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24));
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Show");
        jButton1.setToolTipText("fetch the details");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        products_page.getContentPane().add(jButton1);
        jButton1.setBounds(20, 320, 110, 50);

        jtb1.setBackground(new java.awt.Color(231, 200, 156));
        jtb1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        jtb1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Brand", "colour", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb1.setGridColor(new java.awt.Color(231, 200, 156));
        jtb1.setOpaque(false);
        jScrollPane3.setViewportView(jtb1);

        products_page.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(270, 90, 580, 320);

        jButton20.setBackground(new java.awt.Color(231, 200, 156));
        jButton20.setFont(new java.awt.Font("Arial", 0, 14));
        jButton20.setForeground(new java.awt.Color(204, 0, 0));
        jButton20.setText("CLOSE");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        products_page.getContentPane().add(jButton20);
        jButton20.setBounds(790, 420, 90, 40);

        pr_back.setBackground(new java.awt.Color(231, 200, 156));
        pr_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        products_page.getContentPane().add(pr_back);
        pr_back.setBounds(0, 0, 900, 500);

        dealership.setTitle("Dealership Request");
        dealership.setMinimumSize(new java.awt.Dimension(900, 600));
        dealership.setResizable(false);
        dealership.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40));
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Dealership");
        dealership.getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 10, 250, 40);

        jLabel10.setBackground(new java.awt.Color(193, 130, 47));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Dealer name");
        dealership.getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 150, 140, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Phone");
        dealership.getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 190, 120, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("contract period");
        dealership.getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 350, 160, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("State");
        dealership.getContentPane().add(jLabel13);
        jLabel13.setBounds(260, 270, 110, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("Product");
        dealership.getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 230, 100, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("City");
        dealership.getContentPane().add(jLabel16);
        jLabel16.setBounds(260, 310, 90, 30);

        jt3.setBackground(new java.awt.Color(231, 200, 156));
        jt3.setBorder(null);
        jt3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt3FocusLost(evt);
            }
        });
        dealership.getContentPane().add(jt3);
        jt3.setBounds(510, 150, 120, 30);

        jt4.setBackground(new java.awt.Color(231, 200, 156));
        jt4.setBorder(null);
        jt4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt4FocusLost(evt);
            }
        });
        dealership.getContentPane().add(jt4);
        jt4.setBounds(510, 190, 120, 30);

        jt5.setBackground(new java.awt.Color(231, 200, 156));
        jt5.setBorder(null);
        jt5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt5FocusLost(evt);
            }
        });
        dealership.getContentPane().add(jt5);
        jt5.setBounds(510, 230, 120, 30);

        jt6.setBackground(new java.awt.Color(231, 200, 156));
        jt6.setBorder(null);
        jt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt6ActionPerformed(evt);
            }
        });
        jt6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt6FocusLost(evt);
            }
        });
        dealership.getContentPane().add(jt6);
        jt6.setBounds(510, 270, 120, 30);

        jt7.setBackground(new java.awt.Color(231, 200, 156));
        jt7.setBorder(null);
        jt7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt7FocusLost(evt);
            }
        });
        dealership.getContentPane().add(jt7);
        jt7.setBounds(510, 310, 120, 30);

        jt8.setBackground(new java.awt.Color(231, 200, 156));
        jt8.setBorder(null);
        jt8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt8FocusLost(evt);
            }
        });
        dealership.getContentPane().add(jt8);
        jt8.setBounds(510, 350, 120, 30);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24));
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("<html><head><u>Enter Details</u></head></html>");
        dealership.getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 70, 170, 40);

        jButton6.setBackground(new java.awt.Color(231, 200, 156));
        jButton6.setFont(new java.awt.Font("Arial", 0, 24));
        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("Submit");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        dealership.getContentPane().add(jButton6);
        jButton6.setBounds(320, 410, 120, 60);

        jl7.setFont(new java.awt.Font("Arial", 0, 18));
        jl7.setForeground(new java.awt.Color(255, 0, 51));
        jl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dealership.getContentPane().add(jl7);
        jl7.setBounds(30, 480, 840, 70);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel28.setForeground(new java.awt.Color(238, 20, 20));
        jLabel28.setText("Years");
        dealership.getContentPane().add(jLabel28);
        jLabel28.setBounds(640, 350, 50, 30);

        jButton21.setBackground(new java.awt.Color(231, 200, 156));
        jButton21.setFont(new java.awt.Font("Arial", 0, 14));
        jButton21.setForeground(new java.awt.Color(204, 0, 0));
        jButton21.setText("CLOSE");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        dealership.getContentPane().add(jButton21);
        jButton21.setBounds(790, 500, 90, 50);

        jButton26.setBackground(new java.awt.Color(231, 200, 156));
        jButton26.setFont(new java.awt.Font("Arial", 0, 18));
        jButton26.setForeground(new java.awt.Color(204, 0, 0));
        jButton26.setText("<html><body align=\"center\"><p>Cancel</p><p>Dealership</p></body></html>");
        jButton26.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        dealership.getContentPane().add(jButton26);
        jButton26.setBounds(470, 410, 120, 60);

        ds_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        dealership.getContentPane().add(ds_back);
        ds_back.setBounds(0, 0, 930, 600);

        empl.setTitle("Employee corner");
        empl.setMinimumSize(new java.awt.Dimension(1090, 650));
        empl.setResizable(false);
        empl.getContentPane().setLayout(null);

        jButton14.setBackground(new java.awt.Color(231, 200, 156));
        jButton14.setFont(new java.awt.Font("Arial", 0, 18));
        jButton14.setForeground(new java.awt.Color(255, 0, 51));
        jButton14.setText("Back");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        empl.getContentPane().add(jButton14);
        jButton14.setBounds(900, 570, 70, 50);
        jButton14.setVisible(false);

        jButton22.setBackground(new java.awt.Color(231, 200, 156));
        jButton22.setFont(new java.awt.Font("Arial", 1, 14));
        jButton22.setForeground(new java.awt.Color(255, 0, 51));
        jButton22.setText("CLOSE");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        empl.getContentPane().add(jButton22);
        jButton22.setBounds(980, 570, 90, 50);

        jl48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11-big.jpg"))); // NOI18N
        jl48.setVisible(true);
        empl.getContentPane().add(jl48);
        jl48.setBounds(130, 260, 840, 280);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36));
        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Employee Section");
        empl.getContentPane().add(jLabel19);
        jLabel19.setBounds(370, 30, 320, 40);

        jp2.setVisible(false);
        jp2.setForeground(new java.awt.Color(204, 0, 0));
        jp2.setOpaque(false);
        jp2.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("Name");
        jp2.add(jLabel20);
        jLabel20.setBounds(30, 40, 220, 17);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("Address");
        jp2.add(jLabel21);
        jLabel21.setBounds(30, 70, 220, 17);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("Date Of Birth");
        jp2.add(jLabel22);
        jLabel22.setBounds(30, 100, 220, 17);

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("Sex");
        jp2.add(jLabel23);
        jLabel23.setBounds(30, 130, 220, 17);

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("Department");
        jp2.add(jLabel24);
        jLabel24.setBounds(30, 160, 220, 20);

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("Date Of Joining");
        jp2.add(jLabel25);
        jLabel25.setBounds(30, 190, 220, 17);

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("Mobile Number");
        jp2.add(jLabel26);
        jLabel26.setBounds(30, 220, 220, 17);

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setText("Password");
        jp2.add(jLabel27);
        jLabel27.setBounds(30, 250, 220, 17);

        jt21.setBackground(new java.awt.Color(231, 200, 156));
        jt21.setBorder(null);
        jt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt21ActionPerformed(evt);
            }
        });
        jp2.add(jt21);
        jt21.setBounds(250, 40, 100, 20);

        jt22.setBackground(new java.awt.Color(231, 200, 156));
        jt22.setBorder(null);
        jp2.add(jt22);
        jt22.setBounds(250, 70, 100, 20);

        jt23.setBackground(new java.awt.Color(231, 200, 156));
        jt23.setBorder(null);
        jp2.add(jt23);
        jt23.setBounds(250, 100, 100, 20);

        jt24.setBackground(new java.awt.Color(231, 200, 156));
        jt24.setBorder(null);
        jp2.add(jt24);
        jt24.setBounds(250, 130, 100, 20);

        jt25.setBackground(new java.awt.Color(231, 200, 156));
        jt25.setBorder(null);
        jp2.add(jt25);
        jt25.setBounds(250, 160, 100, 20);

        jt26.setBackground(new java.awt.Color(231, 200, 156));
        jt26.setBorder(null);
        jp2.add(jt26);
        jt26.setBounds(250, 190, 100, 20);

        jt27.setBackground(new java.awt.Color(231, 200, 156));
        jt27.setBorder(null);
        jp2.add(jt27);
        jt27.setBounds(250, 220, 100, 20);

        jButton11.setBackground(new java.awt.Color(231, 200, 156));
        jButton11.setFont(new java.awt.Font("Arial", 0, 14));
        jButton11.setForeground(new java.awt.Color(255, 0, 51));
        jButton11.setText("Submit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jp2.add(jButton11);
        jButton11.setBounds(20, 290, 140, 25);

        jButton15.setBackground(new java.awt.Color(231, 200, 156));
        jButton15.setFont(new java.awt.Font("Arial", 0, 14));
        jButton15.setForeground(new java.awt.Color(255, 0, 51));
        jButton15.setText("Clear");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jp2.add(jButton15);
        jButton15.setBounds(220, 330, 70, 25);

        jLabel33.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel33.setForeground(new java.awt.Color(204, 0, 0));
        jLabel33.setText("ID");
        jp2.add(jLabel33);
        jLabel33.setBounds(30, 10, 220, 17);

        jt29.setBackground(new java.awt.Color(231, 200, 156));
        jt29.setBorder(null);
        jp2.add(jt29);
        jt29.setBounds(250, 10, 100, 20);

        jButton16.setBackground(new java.awt.Color(231, 200, 156));
        jButton16.setFont(new java.awt.Font("Arial", 0, 14));
        jButton16.setForeground(new java.awt.Color(255, 0, 51));
        jButton16.setText("Update Records");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jp2.add(jButton16);
        jButton16.setBounds(170, 290, 140, 25);

        jButton17.setBackground(new java.awt.Color(231, 200, 156));
        jButton17.setFont(new java.awt.Font("Arial", 0, 14));
        jButton17.setForeground(new java.awt.Color(255, 0, 51));
        jButton17.setText("Delete Records");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jp2.add(jButton17);
        jButton17.setBounds(320, 290, 140, 25);

        jt28.setBackground(new java.awt.Color(231, 200, 156));
        jt28.setBorder(null);
        jp2.add(jt28);
        jt28.setBounds(250, 250, 100, 20);

        jLabel34.setForeground(new java.awt.Color(204, 0, 0));
        jLabel34.setText("DD/MM/YYYY");
        jp2.add(jLabel34);
        jLabel34.setBounds(360, 190, 90, 20);

        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("DD/MM/YYYY");
        jp2.add(jLabel35);
        jLabel35.setBounds(360, 100, 90, 20);

        empl.getContentPane().add(jp2);
        jp2.setBounds(340, 200, 480, 380);

        jButton7.setBackground(new java.awt.Color(231, 200, 156));
        jButton7.setFont(new java.awt.Font("Arial", 0, 18));
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("Submit Report");
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        empl.getContentPane().add(jButton7);
        jButton7.setBounds(730, 130, 240, 80);

        jButton10.setBackground(new java.awt.Color(231, 200, 156));
        jButton10.setFont(new java.awt.Font("Arial", 0, 18));
        jButton10.setForeground(new java.awt.Color(255, 0, 51));
        jButton10.setText("New Employee Registration");
        jButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        empl.getContentPane().add(jButton10);
        jButton10.setBounds(130, 130, 240, 80);

        jp1.setVisible(false);
        jp1.setOpaque(false);
        jp1.setLayout(null);

        jLabel17.setBackground(new java.awt.Color(231, 200, 156));
        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22));
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Name");
        jp1.add(jLabel17);
        jLabel17.setBounds(50, 30, 180, 30);

        jt10.setBackground(new java.awt.Color(231, 200, 156));
        jt10.setForeground(new java.awt.Color(204, 0, 0));
        jt10.setBorder(null);
        jp1.add(jt10);
        jt10.setBounds(220, 30, 100, 30);

        jpass.setBackground(new java.awt.Color(231, 200, 156));
        jpass.setForeground(new java.awt.Color(204, 0, 0));
        jpass.setBorder(null);
        jp1.add(jpass);
        jpass.setBounds(220, 70, 100, 30);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22));
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Password");
        jp1.add(jLabel18);
        jLabel18.setBounds(50, 70, 180, 40);

        jButton8.setBackground(new java.awt.Color(231, 200, 156));
        jButton8.setFont(new java.awt.Font("Arial", 0, 14));
        jButton8.setForeground(new java.awt.Color(204, 0, 0));
        jButton8.setText("Login");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jp1.add(jButton8);
        jButton8.setBounds(130, 130, 80, 40);

        empl.getContentPane().add(jp1);
        jp1.setBounds(350, 100, 350, 190);

        empl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        empl.getContentPane().add(empl_back);
        empl_back.setBounds(0, 0, 1180, 650);

        report.setTitle("Submit Report");
        report.setMinimumSize(new java.awt.Dimension(702, 580));
        report.setResizable(false);
        report.getContentPane().setLayout(null);

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36));
        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Submit Report");
        report.getContentPane().add(jLabel29);
        jLabel29.setBounds(210, 10, 270, 60);

        jta10.setColumns(20);
        jta10.setRows(5);
        jScrollPane4.setViewportView(jta10);

        report.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(60, 220, 570, 200);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel30.setForeground(new java.awt.Color(176, 32, 0));
        jLabel30.setText("Department");
        report.getContentPane().add(jLabel30);
        jLabel30.setBounds(60, 160, 150, 20);

        jcb1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jcb1.setForeground(new java.awt.Color(204, 0, 0));
        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marketing", "Sales", "Development", "production", "Accounts" }));
        jcb1.setOpaque(false);
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });
        report.getContentPane().add(jcb1);
        jcb1.setBounds(500, 150, 120, 50);

        jButton12.setFont(new java.awt.Font("Arial", 0, 24));
        jButton12.setForeground(new java.awt.Color(255, 0, 51));
        jButton12.setText("Submit");
        jButton12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        report.getContentPane().add(jButton12);
        jButton12.setBounds(290, 470, 120, 60);

        jl28.setBackground(new java.awt.Color(231, 200, 156));
        jl28.setFont(new java.awt.Font("Arial", 1, 18));
        jl28.setForeground(new java.awt.Color(204, 0, 0));
        jl28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl28.setOpaque(true);
        report.getContentPane().add(jl28);
        jl28.setBounds(220, 80, 250, 50);

        report_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        report_back.setMinimumSize(new java.awt.Dimension(702, 561));
        report.getContentPane().add(report_back);
        report_back.setBounds(0, 0, 700, 560);

        credits.setTitle("Credits");
        credits.setMinimumSize(new java.awt.Dimension(719, 536));
        credits.setResizable(false);
        credits.getContentPane().setLayout(null);

        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24));
        jLabel32.setForeground(new java.awt.Color(255, 204, 0));
        jLabel32.setText("<html><body><p>A PROJECT BY :<p>AASHISH KR. SAHU<p>XII-A<p>ROLL NO. 1 (ONE)</body></html>");
        credits.getContentPane().add(jLabel32);
        jLabel32.setBounds(140, 360, 300, 150);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urban_street-1920x1080.jpg"))); // NOI18N
        jLabel31.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel31.setMinimumSize(new java.awt.Dimension(1366, 768));
        credits.getContentPane().add(jLabel31);
        jLabel31.setBounds(0, 0, 720, 540);

        administrator.setTitle("Administration Department");
        administrator.setMinimumSize(new java.awt.Dimension(800, 600));
        administrator.getContentPane().setLayout(null);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel36.setForeground(new java.awt.Color(204, 0, 0));
        jLabel36.setText("ENTER NAME");
        administrator.getContentPane().add(jLabel36);
        jLabel36.setBounds(210, 90, 240, 40);

        jt45.setBackground(new java.awt.Color(231, 200, 156));
        jt45.setBorder(null);
        jt45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt45ActionPerformed(evt);
            }
        });
        administrator.getContentPane().add(jt45);
        jt45.setBounds(450, 90, 110, 40);

        jl45.setFont(new java.awt.Font("Arial", 1, 18));
        jl45.setForeground(new java.awt.Color(204, 0, 0));
        jl45.setText("ENTER PASSWORD");
        administrator.getContentPane().add(jl45);
        jl45.setBounds(210, 140, 240, 40);

        jt46.setBackground(new java.awt.Color(231, 200, 156));
        jt46.setBorder(null);
        jt46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt46ActionPerformed(evt);
            }
        });
        administrator.getContentPane().add(jt46);
        jt46.setBounds(450, 140, 110, 40);

        jta5.setColumns(20);
        jta5.setRows(5);
        jScrollPane5.setViewportView(jta5);

        administrator.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(96, 266, 610, 200);

        jLabel38.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36));
        jLabel38.setForeground(new java.awt.Color(255, 0, 51));
        jLabel38.setText("Administration");
        administrator.getContentPane().add(jLabel38);
        jLabel38.setBounds(10, 10, 300, 70);

        jButton23.setBackground(new java.awt.Color(231, 200, 156));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton23.setForeground(new java.awt.Color(255, 0, 0));
        jButton23.setText("LOG IN");
        jButton23.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        administrator.getContentPane().add(jButton23);
        jButton23.setBounds(320, 200, 130, 40);

        jButton24.setBackground(new java.awt.Color(231, 200, 156));
        jButton24.setFont(new java.awt.Font("Arial", 0, 18));
        jButton24.setForeground(new java.awt.Color(204, 0, 0));
        jButton24.setText("SHOW");
        jButton24.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/89428.jpg")))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        administrator.getContentPane().add(jButton24);
        jButton24.setBounds(320, 200, 130, 40);
        jButton24.setVisible(false);

        jButton25.setBackground(new java.awt.Color(231, 200, 156));
        jButton25.setFont(new java.awt.Font("Arial", 0, 14));
        jButton25.setForeground(new java.awt.Color(204, 0, 0));
        jButton25.setText("CLOSE");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        administrator.getContentPane().add(jButton25);
        jButton25.setBounds(660, 510, 90, 40);

        admin_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        administrator.getContentPane().add(admin_back);
        admin_back.setBounds(0, -6, 800, 610);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shree Cement");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 498));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 112, 60);

        jTextArea2.setBackground(new java.awt.Color(231, 200, 156));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 13));
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\n We differentiate ourselves in a highly competitive market with continual changes in \n our marketing & branding strategy and by aligning our offerings to the customer's needs instead of forcefully pushing products.\n This is to say we do not create customers, we create what customers want.\n\n We believe that our sustained success is because of our highly satisfied customers and that continuous learning \n about their psyche and behavior is the only path ahead.\n Today, by creating depth in dealer networks, extensive brand promotion and opening up new strategic markets, we are able \n to absorb a larger sales quantum, ensure better realizations and increase our competitiveness. ");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 130, 750, 160);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel5.setForeground(new java.awt.Color(241, 208, 161));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Our Brands");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 330, 140, 50);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton3.setText("Products");
        jButton3.setToolTipText("Product Information");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 90, 103, 30);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton2.setText("About Us");
        jButton2.setToolTipText("About Us");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 90, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/89428.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 20, 530, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shree_ultra.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 300, 120, 140);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bangur.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(157, 205));
        jLabel7.setMinimumSize(new java.awt.Dimension(157, 205));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 300, 130, 150);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockstrong.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(157, 205));
        jLabel8.setMinimumSize(new java.awt.Dimension(157, 205));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 300, 120, 150);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton5.setText("Dealership");
        jButton5.setToolTipText("Apply for Dealership");
        jButton5.setBorderPainted(false);
        jButton5.setMaximumSize(new java.awt.Dimension(45, 17));
        jButton5.setMinimumSize(new java.awt.Dimension(45, 17));
        jButton5.setOpaque(false);
        jButton5.setPreferredSize(new java.awt.Dimension(45, 17));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 90, 103, 30);

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton9.setText("Employee Corner");
        jButton9.setToolTipText("Employee Section");
        jButton9.setBorderPainted(false);
        jButton9.setMaximumSize(new java.awt.Dimension(45, 17));
        jButton9.setMinimumSize(new java.awt.Dimension(45, 17));
        jButton9.setOpaque(false);
        jButton9.setPreferredSize(new java.awt.Dimension(45, 17));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(400, 90, 150, 30);

        jButton13.setBackground(new java.awt.Color(231, 200, 156));
        jButton13.setFont(new java.awt.Font("Baskerville Old Face", 1, 12));
        jButton13.setForeground(new java.awt.Color(204, 0, 0));
        jButton13.setText("<html><body align=\"center\"><p>MEET</p><p>THE</p><p>DEVELOPER</p></body></html>");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(670, 20, 120, 70);

        jButton18.setBackground(new java.awt.Color(231, 200, 156));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton18.setText("Administrator");
        jButton18.setBorder(null);
        jButton18.setOpaque(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(560, 90, 120, 30);

        jButton27.setBackground(new java.awt.Color(231, 200, 156));
        jButton27.setFont(new java.awt.Font("Arial", 0, 24));
        jButton27.setForeground(new java.awt.Color(204, 0, 0));
        jButton27.setText("EXIT");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(700, 410, 90, 50);

        background.setFont(new java.awt.Font("Tahoma", 0, 14));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bground_Texture.jpg"))); // NOI18N
        background.setText("jLabel9");
        background.setMaximumSize(new java.awt.Dimension(1280, 720));
        background.setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
about_us.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
products_page.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr1ActionPerformed


// TODO add your handling code here:
}//GEN-LAST:event_jr1ActionPerformed

    private void jr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr2ActionPerformed
 DefaultTableModel m=(DefaultTableModel)jtb1.getModel();
int a= m.getRowCount();
for(int j=0; j<a; j++)
m.removeRow(0);

// TODO add your handling code here:
    }//GEN-LAST:event_jr2ActionPerformed

    private void jr1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jr1ItemStateChanged
if(jr1.isSelected()==true)
{ jl1.setVisible(true);
    jt1.setVisible(true);}
else
{jl1.setVisible(false);
    jt1.setVisible(false);}
       DefaultTableModel m=(DefaultTableModel)jtb1.getModel();
int a= m.getRowCount();
for(int j=0; j<a; j++)
m.removeRow(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jr1ItemStateChanged

    private void jr2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jr2ItemStateChanged
if(jr2.isSelected()==true)
{ jl2.setVisible(true);
    jt2.setVisible(true);}
else
{jl2.setVisible(false);
    jt2.setVisible(false);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jr2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel m=(DefaultTableModel)jtb1.getModel();
int a= m.getRowCount();
for(int j=0; j<a; j++)
m.removeRow(0);
int r;
String z;
String q = null;
if(jr1.isSelected()==true)
{   r=Integer.parseInt(jt1.getText());
    q="select * from products where pid="+r;}
else
    if(jr2.isSelected()==true)
    {   z = jt2.getText();
q="select * from products where name like '"+z+"%'";}
try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
        ResultSet rs= s.executeQuery(q);
    int i;
    String n,o,p,t,u;
    while(rs.next())
    {i=rs.getInt("pid");
     n=rs.getString("name");
     o=rs.getString("category");
     p=rs.getString("brand");
     t=rs.getString("colour");
     u=rs.getString("availability");
    m.addRow(new Object[]{i,n,o,p,t,u});
    }
}catch(Exception e)
{System.out.println(e.getMessage());}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DefaultTableModel m=(DefaultTableModel)jtb1.getModel();
int a= m.getRowCount();
for(int j=0; j<a; j++)
m.removeRow(0);
try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String q="select * from products";
    ResultSet rs= s.executeQuery(q);
    int i;
    String n,o,p,t,u;
    while(rs.next())
    {i=rs.getInt("pid");
     n=rs.getString("name");
     o=rs.getString("category");
     p=rs.getString("brand");
     t=rs.getString("colour");
     u=rs.getString("availability");
    m.addRow(new Object[]{i,n,o,p,t,u});
    }


}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dealership.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jt6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(op==6)
{try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String r,n;
    r=jt4.getText();
    n=jt8.getText();
    String a,b,f,d;
    a=jt3.getText();
    b=jt5.getText();
    f=jt6.getText();
    d=jt7.getText();
    String q="insert into dealership values('"+a+"', '"+r+"', '"+b+"', '"+f+"', '"+d+"', '"+n+"')";
    int i=s.executeUpdate(q);
    if(i>0)
        jl7.setText("your details were sucessfully submitted.");
    else
        jl7.setText("There is a problem with the data entered.");
}catch(Exception e)
{System.out.println(e.getMessage());}
}
else
    JOptionPane.showMessageDialog(null,"No Details Entered");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
jp1.setVisible(true);
jButton7.setVisible(false);
jButton14.setVisible(true);
jButton10.setVisible(false);
jl48.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
empl.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String a;
    a=jt10.getText();
    String p=new String(jpass.getPassword());
    String q="select * from employee where name='"+a+"' and password='"+p+"'";
    ResultSet rs= s.executeQuery(q); 
    if(rs.first()==true)
    {report.show();
        jl28.setText("Welcome "+a);}

    
    else
        JOptionPane.showMessageDialog(null, "sorry, wrong credentials entered");
}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
jButton7.setVisible(false);
jp2.setVisible(true);
jButton10.setVisible(false);
jButton14.setVisible(true);
jl48.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt21ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jt21ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String a,b,d,e,f,g,h,k;
    int j;
    j=Integer.parseInt(jt29.getText());
    a=jt21.getText();
    b=jt22.getText();
    d=jt23.getText();
    e=jt24.getText();
    f=jt25.getText();
    g=jt26.getText();
    h=jt27.getText(); 
    k=jt28.getText();
    String q="insert into employee values("+j+", '"+a+"', '"+b+"', '"+d+"', '"+e+"', '"+f+"', '"+g+"', '"+h+"', '"+k+"')";
    int i=s.executeUpdate(q);
    if(i>0)
        JOptionPane.showMessageDialog(null, "your details were sucessfully submitted. welcome to shree cement");
    else
        JOptionPane.showMessageDialog(null, "There is a problem with the data entered, please check the data entered or try after a few hours ");
}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
credits.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
jp1.setVisible(false);
jp2.setVisible(false);
jButton7.setVisible(true);
jButton14.setVisible(false);
jButton10.setVisible(true);
jl48.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
jt21.setText("");
jt22.setText("");
jt23.setText("");
jt24.setText("");
jt25.setText("");
jt26.setText("");
jt27.setText("");
jt28.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jcb1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
String a,q,n,k;
k=jt10.getText();
a=jta10.getText();
int i;
i=jcb1.getSelectedIndex();
n=(String)jcb1.getSelectedItem();
q="insert into report values('"+k+"', '"+n+"', '"+a+"')";
    int j=s.executeUpdate(q);
   if(j>0)
      JOptionPane.showMessageDialog(null, "Your report was successfully submitted");
   else
      JOptionPane.showMessageDialog(null, "There was a problem submitting your report, please try again");
}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String a,b,d,e,f,g,h,k;
    int j;
    j=Integer.parseInt(jt29.getText());
    a=jt21.getText();
    b=jt22.getText();
    d=jt23.getText();
    e=jt24.getText();
    f=jt25.getText();
    g=jt26.getText();
    h=jt27.getText();
    k=jt28.getText();
   String q="update employee set name='"+a+"', address= '"+b+"', date_of_birth= '"+d+"', sex='"+e+"', department= '"+f+"',date_of_joining= '"+g+"', mobile_number= '"+h+"', password= '"+k+"' where id="+j;
int i=s.executeUpdate(q);
if(i>0)
    JOptionPane.showMessageDialog(null, "Your records were successfully updated");
else
       JOptionPane.showMessageDialog(null, "error updating records, please try again");

}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
     try
{
    Class.forName("java.sql.Driver");
    Connection c= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    int j=Integer.parseInt(jt29.getText());
    String p=new String(jt28.getPassword());
    String q="delete from employee where id="+j+" and password='"+p+"'";
    int i= s.executeUpdate(q);

    if(i>0)
        JOptionPane.showMessageDialog(null, "record Deleted");
    else
        JOptionPane.showMessageDialog(null, "Error Deleting Records");


     }catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
administrator.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
about_us.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        jt2.setText("");
        jt1.setText("");
        {products_page.dispose();}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
     dealership.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
     empl.dispose();
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jt45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt45ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jt45ActionPerformed

    private void jt46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt46ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jt46ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String a;
        a=jt45.getText();
        String p=new String(jt46.getPassword());
    String q="select * from admin where name='"+a+"' and password='"+p+"'";
    ResultSet rs= s.executeQuery(q);
    if(rs.first()==true)
    {jl45.setVisible(false);
     jt46.setVisible(false);
     jButton23.setVisible(false);
     jButton24.setVisible(true);
     jt45.setText("");
    }
    else
        JOptionPane.showMessageDialog(null, "sorry, wrong credentials entered");
}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String w=jt45.getText();
    String q="select* from report where name='"+w+"'";
    ResultSet rs=s.executeQuery(q);
    rs.first();
    String a= rs.getString("name"),b= rs.getString("department"),z= rs.getString("report");
    jta5.append(" employee : "+a+"\n department : "+b+"\n reprt details: \n"+z);
}catch(Exception e)
{System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed
int op;
    private void jt3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt3FocusLost
        // TODO add your handling code here:
      if (jt3.getText()==null && jt3.getText()=="")
          op=op;
      else
          op=op+1;

    }//GEN-LAST:event_jt3FocusLost

    private void jt4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt4FocusLost
      if (jt4.getText()==null && jt4.getText()=="")
          op=op;
      else
          op=op+1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jt4FocusLost

    private void jt5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt5FocusLost
  if (jt5.getText()==null && jt5.getText()=="")
          op=op;
  else
          op=op+1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jt5FocusLost

    private void jt6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt6FocusLost
  if (jt6.getText()==null && jt6.getText()=="")
          op=op;
  else
          op=op+1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jt6FocusLost

    private void jt7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt7FocusLost
      if (jt7.getText()==null && jt7.getText()=="")
          op=op;
      else
          op=op+1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jt7FocusLost

    private void jt8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt8FocusLost
  if (jt8.getText()==null && jt8.getText()=="")
          op=op;
      else
          op=op+1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jt8FocusLost

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
administrator.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "123");
    Statement s= c.createStatement();
    String g=jt3.getText();
    String q="delete from dealership where name like'"+g+"'";
    int i=s.executeUpdate(q);
    if(i>0)
        JOptionPane.showMessageDialog(null, "Dealership Cancelled");
    else
        JOptionPane.showMessageDialog(null, "error connecting to the server");
}catch(Exception e)
{System.out.println(e.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
JOptionPane.showMessageDialog(null, "THANK YOU, PLEASE VISIT AGAIN");
{ System.exit(0);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog about_us;
    private javax.swing.JLabel admin_back;
    private javax.swing.JDialog administrator;
    private javax.swing.JLabel au_back;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog credits;
    private javax.swing.JDialog dealership;
    private javax.swing.JLabel ds_back;
    private javax.swing.JDialog empl;
    private javax.swing.JLabel empl_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl28;
    private javax.swing.JLabel jl45;
    private javax.swing.JLabel jl48;
    private javax.swing.JLabel jl7;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JRadioButton jr1;
    private javax.swing.JRadioButton jr2;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt10;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt21;
    private javax.swing.JTextField jt22;
    private javax.swing.JTextField jt23;
    private javax.swing.JTextField jt24;
    private javax.swing.JTextField jt25;
    private javax.swing.JTextField jt26;
    private javax.swing.JTextField jt27;
    private javax.swing.JPasswordField jt28;
    private javax.swing.JTextField jt29;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt45;
    private javax.swing.JPasswordField jt46;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    private javax.swing.JTextArea jta10;
    private javax.swing.JTextArea jta5;
    private javax.swing.JTable jtb1;
    private javax.swing.JLabel pr_back;
    private javax.swing.JDialog products_page;
    private javax.swing.JDialog report;
    private javax.swing.JLabel report_back;
    // End of variables declaration//GEN-END:variables

}
